version: '2'
services:
  web:
    image: tomcat:8.5
    ports: 
      - "8080:8080"
    volumes:
      - ./target/JavaProjectExample.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/JavaProjectExample:/usr/local/tomcat/webapps/ROOT
